import { NextRequest, NextResponse } from 'next/server';
import JSZip from 'jszip';

/**
 * This route handles the creation of a ZIP file from the generated project files.
 * It allows users to download their code for local use.
 */
export async function POST(req: NextRequest) {
  try {
    const { files } = await req.json();

    if (!files || !Array.isArray(files)) {
      return NextResponse.json(
        { error: 'Files array is required' },
        { status: 400 }
      );
    }

    const zip = new JSZip();

    // Loop through the files generated by the AI
    files.forEach((file: { path: string; content: string }) => {
      if (file.path && file.content !== undefined) {
        zip.file(file.path, file.content);
      }
    });

    // Generate the ZIP as a buffer
    const blob = await zip.generateAsync({ type: 'nodebuffer' });

    // Return the ZIP file with appropriate headers
    return new NextResponse(blob, {
      status: 200,
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': 'attachment; filename="project-export.zip"',
      },
    });
  } catch (error: any) {
    console.error('ZIP Creation Error:', error);
    return NextResponse.json(
      { error: 'Failed to create ZIP archive: ' + error.message },
      { status: 500 }
    );
  }
}
